SCR.Root/Controllers/SyncRealtorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SCR.Root.Models;
using System.Net;
using System.Text;
using System.IO;
using SCR.Root.App_Code;
using System.Globalization;
using Newtonsoft.Json;
using System.Data;
using System.Threading;
using System.Configuration;

namespace SCR.Root.Controllers
{
    public class SyncRealtorsController : Controller
    {
        //
        // GET: /SyncRealtors/

        bool boolUpdate = false;
        bool boolAddNRDS = false;
        bool boolIsMemberFile;
        bool boolOfficeResult = false;
        bool boolres = false;
        int insertCount = -1;
        int resultPerc = -1;
        double insertPerc;

        string strDirpath = ConfigurationManager.AppSettings["DirPath"].ToString();
        string strRarfilepath = ConfigurationManager.AppSettings["RarFilePath"].ToString();
        string strZipfilepath = ConfigurationManager.AppSettings["ZipFilePath"].ToString();



        public ActionResult Sync()
        {
            SyncRealtorsModel objSyncRealtorsModel = new SyncRealtorsModel();
            return View(objSyncRealtorsModel);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Sync(SyncRealtorsModel objSyncRealtorsModel, HttpPostedFileBase fupdCSVUpload, HttpPostedFileBase fupdCSVUpload1)
        {

            UserSession userSession = new UserSession();
            if (userSession.Exists)
            {
                try
                {

                    string strfileType = string.Empty;
                    string strfilePath = string.Empty;
                    string strfileLength = string.Empty;
                    string ext = string.Empty;
                   

                    #region File save
                    //check to make sure a file is selected
                    if (fupdCSVUpload != null)
                    {
                        //create the path to save the file to
                        string filename = fupdCSVUpload.FileName;


                        if (filename.Length != 0)
                        {
                            ext = Path.GetExtension(filename);


                            if (ext.ToLower() == ".zip")//ext.ToLower() == ".rar" ||
                            {


                                if (!Directory.Exists(strDirpath))
                                {
                                    Directory.CreateDirectory(strDirpath);
                                }

                                strfilePath = Path.Combine(strDirpath, fupdCSVUpload.FileName);
                               
                                    if (filename.ToUpper().Contains("O00"))
                                    {
                                        boolIsMemberFile = false;
                                        objSyncRealtorsModel.HddnBoolIsMemberFile = 0;

                                    }
                                    else if (filename.ToUpper().Contains("M00"))
                                    {
                                        boolIsMemberFile = true;
                                        objSyncRealtorsModel.HddnBoolIsMemberFile = 1;
                                    }

                                    strfileType = fupdCSVUpload.ContentType;
                                    strfileLength = Convert.ToString(fupdCSVUpload.ContentLength);
                                

                                //save the file to our local path
                                    //if (filename.ToUpper().Contains(".RAR"))
                                    //{
                                    //    fupdCSVUpload.SaveAs(strRarfilepath);
                                    //}
                                  //  else
                                 
                                if (filename.ToUpper().Contains(".ZIP"))

                                    {
                                        fupdCSVUpload.SaveAs(strZipfilepath);
                                    }

                                TempData["error"] = "File uploaded successfully.";
                                TempData["errtitle"] = "Sync Realtors";
                                TempData["errType"] = "success";
                                return View(objSyncRealtorsModel);
                            }
                            else
                            {
                                TempData["error"] = "Allowed only files with .zip extention.";
                                TempData["errtitle"] = "Sync Realtors";
                                TempData["errType"] = "warning";
                                return View(objSyncRealtorsModel);
                            }
                        }
                        else
                        {
                            TempData["error"] = "Please upload file.";
                            TempData["errtitle"] = "Sync Realtors";
                            TempData["errType"] = "warning";
                            return View(objSyncRealtorsModel);
                        }

                    #endregion File save

                        #region Read data from CSV file

                        /*//
                        using (CsvFileReader reader = new CsvFileReader(strfilePath))
                        {
                            CsvRow row = new CsvRow();
                            int i = 0;
                            while (reader.ReadRow(row))
                            {
                                i++;
                                if (i == 7)
                                {
                                    objSyncRealtorsModel.Filename = filename.Trim();
                                    objSyncRealtorsModel.Hddnfilepath = strfilePath.Trim();
                                    objSyncRealtorsModel.HddnTransmittalBatchNumber = Convert.ToInt32(row[2]);
                                    objSyncRealtorsModel.HddnTransactionTotal = Convert.ToInt32(row[4]);
                                }

                            }
                        }*/
                        #endregion Read data from CSV file

                   
                    }

                    else  if (fupdCSVUpload1 != null)
                    {
                        //create the path to save the file to
                        string filename = fupdCSVUpload1.FileName;


                        if (filename.Length != 0)
                        {
                            ext = Path.GetExtension(filename);


                            if (ext.ToLower() == ".xls")//ext.ToLower() == ".rar" ||
                            {


                                if (!Directory.Exists(strDirpath))
                                {
                                    Directory.CreateDirectory(strDirpath);
                                }

                                strfilePath = Path.Combine(strDirpath, fupdCSVUpload1.FileName);
                               
                                    //if (filename.ToUpper().Contains("O00"))
                                    //{
                                    //    boolIsMemberFile = false;
                                    //    objSyncRealtorsModel.HddnBoolIsMemberFile = 0;

                                    //}
                                    //else if (filename.ToUpper().Contains("M00"))
                                    //{
                                    //    boolIsMemberFile = true;
                                    //    objSyncRealtorsModel.HddnBoolIsMemberFile = 1;
                                    //}

                                   // strfileType = fupdCSVUpload.ContentType;
                                   // strfileLength = Convert.ToString(fupdCSVUpload.ContentLength);
                                

                                //save the file to our local path
                                    //if (filename.ToUpper().Contains(".RAR"))
                                    //{
                                    //    fupdCSVUpload.SaveAs(strRarfilepath);
                                    //}
                                  //  else
                                string path_act = strDirpath + filename;
                                if (filename.ToUpper().Contains(".XLS"))

                                    {
                                        fupdCSVUpload1.SaveAs(path_act);
                                    }

                                TempData["error"] = "File uploaded successfully.";
                                TempData["errtitle"] = "Sync Realtors";
                                TempData["errType"] = "success";
                                return View(objSyncRealtorsModel);
                            }
                            else
                            {
                                TempData["error"] = "Allowed only files with .zip extention.";
                                TempData["errtitle"] = "Sync Realtors";
                                TempData["errType"] = "warning";
                                return View(objSyncRealtorsModel);
                            }
                        }
                        else
                        {
                            TempData["error"] = "Please upload file.";
                            TempData["errtitle"] = "Sync Realtors";
                            TempData["errType"] = "warning";
                            return View(objSyncRealtorsModel);
                        }

                   


                   
                    }

                }

SCR.Root/Views/SyncRealtors/Add.cshtml
@model SCR.Root.Models.SyncRealtorsModel
@{
    ViewBag.Title = "Sync Realtors";
    Layout = "~/Views/Shared/_SCRLayout.cshtml";
}
@using (Html.BeginForm("Add", "SyncRealtors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary();
    <div>
        @Html.HiddenFor(model => model.LLRId)
        <div class="block-fluid without-head span9">
            <div class="row-form clearfix">
                <div class="span3">LLR CSV File</div>
                <div class="span9" style="width: 300px">
                    <input id="fupdCSVUpload" type="file" accept="image/*"/>                   
                </div>
            </div>
        </div>
        <div class="span9">
            <button id="btnSync" class="btn" runat="server">Sync</button>
        </div>
    </div>
    
}


SCR.Root/Views/SyncRealtors/Sync.cshtml
@model SCR.Root.Models.SyncRealtorsModel
@{
    ViewBag.Title = "Import Realtors";
    Layout = "~/Views/Shared/_SCRLayout.cshtml";
}
<script type='text/javascript' src="~/js/plugins/pnotify/jquery.pnotify.min.js"></script>
<script type='text/javascript' src="~/js/plugins.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        Notifybox();
    });

    function Notifybox() {
       
        if (('@TempData["error"]' != null && '@TempData["error"]' != "") && ('@TempData["errtitle"]' != "" && '@TempData["errtitle"]' != null)) {
            debugger;
            var message = '@TempData["error"]';
            var Title = '@TempData["errtitle"]';
            var ErrorType = '@TempData["errType"]';

            var errors = '@TempData.Remove("error")';
            var errtitles = '@TempData.Remove("errtitle")';
            var errTypes = '@TempData.Remove("errType")';

            if (ErrorType == "" && ErrorType == null) {
                ErrorType = "warning";
            }

            if (ErrorType == "success") {

                notify_s(Title, message);
            }
            else if (ErrorType == "info") {
                notify_i(Title, message);
            }
            else if (ErrorType == "error") {
                notify_e(Title, message);
            }
            else {
                notify(Title, message);
            }
          
        }
        else {
            var errors = '@TempData.Remove("error")';
            var errtitles = '@TempData.Remove("errtitle")';
            var errTypes = '@TempData.Remove("errType")';
            return true;
        }
    }
</script>

@* Geethanjali for Progress Bar *@

<script type="text/javascript">


    $(function () {

        $("#btnUpload").click(function () {
            debugger;
            var filePath = $("#fUpload").val();

            if (filePath == "")
            {
                notify("Import Realtors", "Please select a file");
                $("#divLoading").hide();
                return false;
            }

        })

    });

    $(function () {
        $("#btnSync").click(function () {
            debugger;
            var filePath = $("#Hddn_filepath").val();
            var boolIsMemberFile = $("#Hddn_BoolIsMemberFile").val();
            //alert('filePath:' + filePath);
            if (filePath != "") {
                $.ajax({
                    type: "GET",
                    url: '/SyncRealtors/DataImportCSV',
                    cache: false,
                    data: { 'filePath': filePath, 'boolIsMemberFile': boolIsMemberFile },
                    success: function (response) {
                      
                    }
                });
            }
            // setInterval(function () { UpdateProgressBar() }, 5000); // 1000 ==> 1 second , 60000 ==> 1 minute

            var interval = setInterval(function () {
                UpdateProgressBar();
                

                if ($(".progbar").text().trim() == "Completed") {

                    $(".progbar").css("background-color", "Green");
                    notify("Import Realtors ", "Completed");
                    clearInterval(interval);

                }

            }, 100);
        });
    });

    function UpdateProgressBar() {
        debugger;
        var tran_total = $("#Hddn_TransactionTotal").val();
        var tran_BatchNo = $("#Hddn_TransmittalBatchNumber").val();
        var boolIsMemberFile = $("#Hddn_BoolIsMemberFile").val();
        if (tran_total != 0 && tran_BatchNo != 0) {
            $.ajax
          ({
              type: "GET",
              url: '/SyncRealtors/UpdateProgress',
              data: { 'TranTotal': tran_total, 'TranBatchNumber': tran_BatchNo, 'boolIsMemberFile': boolIsMemberFile },
              cache: false,
              success: function (response) {

                  if (response < "3") { $('.progbar').width("3%"); }
                  else { $('.progbar').width(response + "%"); }


                  if (response == "100") { $(".progbar").text("Completed"); }
                  else { $(".progbar").text(response + "%"); }

              }
          });
        }
    }
</script>

<script type="text/javascript" >

    function JavascriptFunction() {
        debugger;
        var url = '@Url.Action("", "")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    
                });
        //$("#divLoading").hide();
    }
</script>


@using (Html.BeginForm("Sync", "SyncRealtors", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", @id = "validation" }))
{
        @Html.ValidationSummary()

        @Html.Hidden("Hddn_TransactionTotal", Model.HddnTransactionTotal)
        @Html.Hidden("Hddn_TransmittalBatchNumber", Model.HddnTransmittalBatchNumber)
        @Html.Hidden("Hddn_filepath", Model.Hddnfilepath)
         @Html.Hidden("Hddn_BoolIsMemberFile", Model.HddnBoolIsMemberFile )
       
       <div>
        <div class="block-fluid without-head span9" >
            @if (Model.HddnTransactionTotal == 0 && Model.HddnTransmittalBatchNumber == 0)
            {
                <div style="width:100%;">
                <div class="row-form clearfix" id="divUpload" runat="server" style="width:40%; float:left;">
                    <div class="span12">LLR CSV (ZIP FILE) </div>
                    <div class="span12" style="margin-left: 0;">
                        <input type="file" name="fupdCSVUpload" id="fUpload" accept=".M00,.csv,.O00,.zip" title="Click to select file" />

                    </div>
                    @*   <div class="span3"></div>
                  <div class="span9" id="progbar" style="display:none;">
                    <div id="progressbar-2">
                        <div class="elapsed"></div>
                        <div class="percent"></div>
                        <div class="pbar"></div>
                    </div>
                </div>*@
                    <button id="btnUpload" class="btn" onclick="JavascriptFunction()" runat="server" title="Upload">
                    Upload
                 <i> <img src="~/img/Upload_icon.png" class="pull-left imagepadding" /></i>
                </button>
                      <input type="button" id="btnCancel" value="Cancel" class="btn_cancel btn image-button" onclick="window.location = '../SyncRealtors/Sync'" title="Cancel" />  
                </div>

                     <div class="row-form clearfix" id="divUpload1" runat="server"  style="width:40%;float:right;">
                    <div class="span12"> NRDS File (ACTIVE AGENT FILE)</div><br />
                    <div class="span12" style="margin-left:0;">
                        <input type="file" name="fupdCSVUpload1" id="fUpload1" accept=".zip,.xls" title="Click to select file" />

                    </div>
                    @*   <div class="span3"></div>
                  <div class="span9" id="progbar" style="display:none;">
                    <div id="progressbar-2">
                        <div class="elapsed"></div>
                        <div class="percent"></div>
                        <div class="pbar"></div>
                    </div>
                </div>*@
<button id="btnUpload1" class="btn" onclick="JavascriptFunction()" runat="server" title="Upload">
                    Upload
                 <i> <img src="~/img/Upload_icon.png" class="pull-left imagepadding" /></i>
                </button>
                           <input type="button" id="btnCancel" value="Cancel" class="btn_cancel btn image-button" onclick="window.location = '../SyncRealtors/Sync'" title="Cancel" />  
                </div>
                    </div>
                
                
            }
            else
            {
                if (Model.HddnTransactionTotal != 0 && Model.HddnTransmittalBatchNumber != 0)
                {
                <div class="row-form clearfix" id="divImport" runat="server">
                    <div class="span3">@Html.LabelFor(model => model.Filename, "File name", new { @id = "lblFilename" })
                    </div>
                    <div class="span9">@Html.TextBoxFor(model => model.Filename, new { id = "txtFilename", @readonly = "true", @style = "width:40%;height:30px;margin-top:15px;margin:1% 2.5%;resize:none;" })
                    </div>

                </div>
                <div class="progbar" style=" background: #df6e1e;    border-radius:4px;    font-family:calibri;    color:black;    text-align: center; overflow: hidden;  "></div>
                }
            }
        </div>
        <div class="span9">
           @* @if (Model.HddnTransactionTotal != null && Model.HddnTransmittalBatchNumber != null)
            {
                if (Model.HddnTransactionTotal != 0 && Model.HddnTransmittalBatchNumber != 0)
                {                 
                <input id="btnSync" type="button" value="Import" class="btn_cancel  btn upload-button"/>
                
                }
                else
                {
               
                <button id="btnUpload" class="btn" onclick="JavascriptFunction()" runat="server">
                    Upload
                 <i> <img src="~/img/Upload_icon.png" class="pull-left imagepadding" /></i>
                </button>
                }
            } *@   
            
             
            
                   
                       
        </div>
            <div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
                  top: 0px; width: 100%; height: 100%; background-color: none; z-index: 30001;
                opacity: .8; filter: alpha(opacity=70);display:none" >
    <p style="position: absolute; top: 30%; left: 45%; ">
         <img src="~/img/Loading.GIF" />
    </p></div>
    </div>
    
}
